Add dependencies to Dockerfile
OpenConext/OpenConext-containers pull request #8
Opened 2022-03-01 15:26 UTC by VadimSchmitz

To run the tests within Stepup-RA the following things are needed
php gmp (used for composer install)
wget (used to download tests)
yarn (used for yarn audit)

2022-03-02 13:13 UTC, MKodde requested changes
Lookin' good! There is room for some improvement. But you are on the right track!

2022-03-02 13:13 UTC, MKodde commented on docker/php-test-stepup/Dockerfile
> +RUN docker-php-ext-install gmp
Idem for these lines. They can probably be included on the 'Install dependencies' `RUN` section on lines 9..20

2022-03-02 14:11 UTC, VadimSchmitz commented on docker/php-test-stepup/Dockerfile
>  ENV NODE_VERSION 10
Changed to version 14 for now.
For testing yarn is needed which needs a minimum version of node 12

2022-03-03 07:28 UTC, MKodde approved these changes
Thanks for clearing the nits! All is well!

2022-03-07 12:46 UTC, quartje commented
Nice work! 
Maybe not related to this PR, but should we have 2 containers that are more or less the same (the php-test-stepup and php-build-stepup)? Seems like both have the same versions of apps installed, only the test container has slightly more installed, which shouldn't be in the way of the build process.

2022-03-08 07:20 UTC, VadimSchmitz commented
Currently they might look about the same but there is a reason to have a different container for the tag-releases and the test-integration. The main reason is that each container will be responsible for one thing, one for releases and one for testing. Next to this the the PHP-test-stepup container will eventually need more dependencies for testing on other repos.

2022-03-08 10:01 UTC, MKodde commented
As you might expect @quartje I agree with Vadim here. Having one trick pony to perform multiple tasks seems very tempting at this point. And you are correct in stating that the build and test containers are very similar. 

However when we start running into more demanding StepUp applications (like Gateway and other projects that require a webserver to run tests) the number of dependencies installed on the container will start to differ more and more. For example by then we probably want the base image to be php-fpm. And additional webserver config is required to get things into gear.

2022-03-14 09:04 UTC, merged